"use client";

import type {
  ChatModelAdapter,
  ChatModelRunResult,
  ThreadMessage,
} from "@assistant-ui/react";
import type { ReadonlyJSONObject } from "assistant-stream/utils";

import {
  TOKEN_ADJUSTMENT_TOOL_NAME,
  buildTokenChangeSummary,
  type TokenAdjustmentToolArgs,
  type TokenAdjustmentToolResult,
} from "@/lib/runtime/tools/token-tools";
import {
  FOUNDRY_TOKEN_SYNC_TOOL_NAME,
  type FoundryTokenSyncToolArgs,
  type FoundryTokenSyncToolResult,
} from "@/lib/runtime/tools/foundry-token-sync-tool";
import {
  LOAD_BUNDLE_TOOL_NAME,
  type LoadBundleToolArgs,
  type LoadBundleToolResult,
} from "@/lib/runtime/tools/stage1-tools";
import {
  RENDER_COMPONENT_TOOL_NAME,
  renderComponent,
  type RenderComponentToolArgs,
  type RenderComponentToolResult,
} from "@/lib/runtime/tools/oods-tools";
import {
  VALIDATE_SCHEMA_TOOL_NAME,
  validateSchema,
  type ValidateSchemaToolArgs,
  type ValidateSchemaToolResult,
} from "@/lib/runtime/tools/validate-tools";
import {
  SET_DOCUMENT_TOOL_NAME,
  PATCH_NODE_TOOL_NAME,
  SET_DATA_CONTEXT_TOOL_NAME,
  executeSetDataContext,
  type SetDocumentToolResult,
  type PatchNodeToolResult,
  type SetDataContextToolArgs,
  type SetDataContextToolResult,
} from "@/lib/runtime/tools/document-tools";
import {
  COMPONENT_CATALOG_TOOL_NAME,
  executeComponentCatalog,
  type ComponentCatalogToolArgs,
  type ComponentCatalogToolResult,
} from "@/lib/runtime/tools/component-catalog-tool";
import { FORGE_REGENERATE_TOOL_NAME } from "@/lib/runtime/tools/forge-regenerate-tools";
import { useTokenStateStore } from "@/lib/stores/token-state";
import { getComponentCatalogPromptSection } from "@/lib/foundry/catalog";

export type ExecuteToolContext = {
  toolName: string;
  args: Record<string, unknown>;
  toolCallId: string;
  abortSignal: AbortSignal;
};

export type ToolExecuteResult = { error: string } | Record<string, unknown>;

export type ToolEnabledChatModelAdapter = ChatModelAdapter & {
  executeTool: (context: ExecuteToolContext) => Promise<ToolExecuteResult>;
};

type ToolEnabledChatModelAdapterLike = ChatModelAdapter & {
  executeTool?: (context: ExecuteToolContext) => Promise<ToolExecuteResult>;
};

/** Round-trip through JSON to produce a ReadonlyJSONObject-compatible value. */
const toJsonArgs = (args: Record<string, unknown>): ReadonlyJSONObject => {
  const parsed: unknown = JSON.parse(JSON.stringify(args));
  if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
    return parsed as ReadonlyJSONObject;
  }
  return {};
};

const TOKENS_TRIGGER = "/tokens";
const TOKENS_IMPORT_SUBCOMMAND = "import";
const BUNDLE_TRIGGER = "/bundle";
const RENDER_TRIGGER = "/render";
const VALIDATE_TRIGGER = "/validate";
const COMPONENTS_TRIGGER = "/components";

/** Maps slash-command triggers to their corresponding tool names. */
const TRIGGER_TOOL_MAP: Record<string, string> = {
  [TOKENS_TRIGGER]: TOKEN_ADJUSTMENT_TOOL_NAME,
  [BUNDLE_TRIGGER]: LOAD_BUNDLE_TOOL_NAME,
  [RENDER_TRIGGER]: RENDER_COMPONENT_TOOL_NAME,
  [VALIDATE_TRIGGER]: VALIDATE_SCHEMA_TOOL_NAME,
  [COMPONENTS_TRIGGER]: COMPONENT_CATALOG_TOOL_NAME,
};

/** Prefix applied to toolCallIds generated by slash commands.
 *  On re-invocation the presence of this prefix distinguishes
 *  slash-command tool results from LLM-initiated tool results. */
const SLASH_TOOL_PREFIX = "slash:";

const slashToolCallId = (name: string): string =>
  `${SLASH_TOOL_PREFIX}${name}-${Date.now()}-${Math.random()
    .toString(16)
    .slice(2, 8)}`;

const hasSlashToolResult = (message: ThreadMessage): boolean =>
  message.content.some(
    (part) =>
      part.type === "tool-call" &&
      typeof part.toolCallId === "string" &&
      part.toolCallId.startsWith(SLASH_TOOL_PREFIX)
  );

const extractLatestUserText = (
  messages: readonly ThreadMessage[]
): string | null => {
  for (let i = messages.length - 1; i >= 0; i -= 1) {
    const message = messages[i];
    if (message.role !== "user") continue;
    const textParts = message.content
      .filter((part) => part.type === "text")
      .map((part) => part.text);
    const text = textParts.join(" ").trim();
    if (text) return text;
  }
  return null;
};

const normalizeCommand = (text: string): string =>
  text.trim().toLowerCase();

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const parseJsonChanges = (input: string): Record<string, string> | null => {
  try {
    const parsed = JSON.parse(input);
    if (!isRecord(parsed)) {
      return null;
    }

    return Object.entries(parsed).reduce<Record<string, string>>(
      (acc, [key, value]) => {
        const trimmedKey = key.trim();
        if (!trimmedKey) {
          return acc;
        }
        acc[trimmedKey] = String(value);
        return acc;
      },
      {}
    );
  } catch {
    return null;
  }
};

const parseJsonSchema = (input: string): Record<string, unknown> | null => {
  try {
    const parsed = JSON.parse(input);
    return isRecord(parsed) ? parsed : null;
  } catch {
    return null;
  }
};

const parseTokenChanges = (input: string): Record<string, string> => {
  const trimmed = input.trim();
  if (!trimmed) {
    return {};
  }

  if (trimmed.startsWith("{")) {
    const parsed = parseJsonChanges(trimmed);
    if (parsed) {
      return parsed;
    }
  }

  const segments = trimmed.split(/[\n,]+|\s+/).filter(Boolean);
  return segments.reduce<Record<string, string>>((acc, segment) => {
    const eqIndex = segment.indexOf("=");
    if (eqIndex <= 0) {
      return acc;
    }

    const path = segment.slice(0, eqIndex).trim();
    if (!path) {
      return acc;
    }

    const value = segment.slice(eqIndex + 1).trim();
    acc[path] = value;
    return acc;
  }, {});
};

const toTokenBuildString = (value: unknown): string | undefined => {
  if (typeof value === "string" && value.trim()) {
    return value.trim();
  }

  if (isRecord(value) && typeof value.name === "string" && value.name.trim()) {
    return value.name.trim();
  }

  return undefined;
};

const normalizeFoundryTokenTheme = (value: string | undefined): string | undefined => {
  const trimmed = value?.trim();
  if (!trimmed) {
    return undefined;
  }

  const normalized = trimmed.toLowerCase();
  if (normalized === "light" || normalized === "base" || normalized === "default") {
    return "light";
  }
  if (normalized === "dark" || normalized === "night") {
    return "dark";
  }
  if (
    normalized === "hc" ||
    normalized === "high-contrast" ||
    normalized === "high_contrast" ||
    normalized === "highcontrast"
  ) {
    return "hc";
  }

  return trimmed;
};

const normalizeFoundryTokenBrand = (value: string | undefined): string | undefined => {
  const trimmed = value?.trim();
  if (!trimmed) {
    return undefined;
  }

  if (trimmed.toLowerCase() === "default") {
    return "A";
  }

  return trimmed;
};

const parseTokenSyncArgs = (
  input: string
): Pick<FoundryTokenSyncToolArgs, "brand" | "theme"> | null => {
  const trimmed = input.trim();
  if (!trimmed.toLowerCase().startsWith(TOKENS_IMPORT_SUBCOMMAND)) {
    return null;
  }

  const remainder = trimmed.slice(TOKENS_IMPORT_SUBCOMMAND.length).trim();
  if (!remainder) {
    return {};
  }

  if (remainder.startsWith("{")) {
    const parsed = parseJsonSchema(remainder);
    if (!parsed) {
      return {};
    }
    const brand = normalizeFoundryTokenBrand(toTokenBuildString(parsed.brand));
    const theme = normalizeFoundryTokenTheme(toTokenBuildString(parsed.theme));
    if (brand || theme) {
      return { brand, theme };
    }
    return {};
  }

  return { theme: normalizeFoundryTokenTheme(remainder) };
};

const buildTokenAdjustmentCall = (input?: string): ChatModelRunResult => {
  const args: TokenAdjustmentToolArgs = {
    title: "Token adjustments",
    prompt: "Review and apply the proposed token updates.",
    requestId: `tokens-${Date.now()}`,
    changes: parseTokenChanges(input ?? ""),
  };

  return {
    content: [
      { type: "text", text: "Launching token adjustment tool UI." },
      {
        type: "tool-call",
        toolCallId: slashToolCallId("tokens-tool"),
        toolName: TOKEN_ADJUSTMENT_TOOL_NAME,
        args: toJsonArgs(args),
        argsText: JSON.stringify(args),
      },
    ],
    status: {
      type: "requires-action",
      reason: "tool-calls",
    },
  };
};

const buildFoundryTokenSyncCall = (
  syncArgs: Pick<FoundryTokenSyncToolArgs, "brand" | "theme">
): ChatModelRunResult => {
  const args: FoundryTokenSyncToolArgs = {
    title: "Foundry canonical token sync",
    prompt:
      "Import canonical tokens from Foundry and preserve manual overrides in the current workspace.",
    requestId: `tokens-sync-${Date.now()}`,
    preserveManualOverrides: true,
    brand: syncArgs.brand,
    theme: syncArgs.theme,
  };

  return {
    content: [
      { type: "text", text: "Launching Foundry canonical token sync." },
      {
        type: "tool-call",
        toolCallId: slashToolCallId("tokens-sync-tool"),
        toolName: FOUNDRY_TOKEN_SYNC_TOOL_NAME,
        args: toJsonArgs(args),
        argsText: JSON.stringify(args),
      },
    ],
    status: {
      type: "requires-action",
      reason: "tool-calls",
    },
  };
};

const buildLoadBundleCall = (input?: string): ChatModelRunResult => {
  const args: LoadBundleToolArgs = {
    title: "Stage1 bundle ingestion",
    prompt: "Load a Stage1 bundle to extract components and token suggestions.",
    requestId: `bundle-${Date.now()}`,
    bundleJson: input?.trim() || undefined,
  };

  return {
    content: [
      { type: "text", text: "Launching Stage1 bundle ingestion." },
      {
        type: "tool-call",
        toolCallId: slashToolCallId("bundle-tool"),
        toolName: LOAD_BUNDLE_TOOL_NAME,
        args: toJsonArgs(args),
        argsText: JSON.stringify(args),
      },
    ],
    status: {
      type: "requires-action",
      reason: "tool-calls",
    },
  };
};

const buildRenderComponentCall = (input?: string): ChatModelRunResult => {
  const trimmed = input?.trim() ?? "";
  const parsedSchema = trimmed ? parseJsonSchema(trimmed) : null;

  const args: RenderComponentToolArgs = {
    title: "Render component",
    prompt:
      "Set a single-component document and render via the composition preview pipeline.",
    requestId: `render-${Date.now()}`,
    schema: parsedSchema ?? undefined,
    validate: true,
  };

  return {
    content: [
      { type: "text", text: "Applying component document to composition preview." },
      {
        type: "tool-call",
        toolCallId: slashToolCallId("render-tool"),
        toolName: RENDER_COMPONENT_TOOL_NAME,
        args: toJsonArgs(args),
        argsText: JSON.stringify(args),
      },
    ],
    status: {
      type: "requires-action",
      reason: "tool-calls",
    },
  };
};

const buildValidateSchemaCall = (input?: string): ChatModelRunResult => {
  const trimmed = input?.trim() ?? "";
  const parsedSchema = trimmed ? parseJsonSchema(trimmed) : null;

  const args: ValidateSchemaToolArgs = {
    title: "Schema validation",
    prompt: "Validate a component schema via Foundry MCP.",
    requestId: `validate-${Date.now()}`,
    schema: parsedSchema ?? undefined,
  };

  return {
    content: [
      { type: "text", text: "Launching schema validation." },
      {
        type: "tool-call",
        toolCallId: slashToolCallId("validate-tool"),
        toolName: VALIDATE_SCHEMA_TOOL_NAME,
        args: toJsonArgs(args),
        argsText: JSON.stringify(args),
      },
    ],
    status: {
      type: "requires-action",
      reason: "tool-calls",
    },
  };
};

const buildComponentCatalogCall = async (): Promise<ChatModelRunResult> => {
  try {
    const { snapshot } = await getComponentCatalogPromptSection({ limit: 120 });
    const args: ComponentCatalogToolArgs = {
      requestId: `components-${Date.now()}`,
      title: "Available components",
      prompt:
        snapshot.source === "foundry"
          ? "Catalog loaded from Foundry structured data."
          : "Catalog loaded from fallback component registry.",
      source: snapshot.source,
      generatedAt: snapshot.catalog.generatedAt,
      componentCount: snapshot.catalog.componentCount,
      components: snapshot.catalog.components.slice(0, 120).map((component) => ({
        id: component.id,
        name: component.name,
        description: component.description,
        requiredProps: component.requiredProps,
        traits: component.traits,
        variants: component.variants,
      })),
    };

    return {
      content: [
        {
          type: "text",
          text: `Loaded ${snapshot.catalog.componentCount} component${
            snapshot.catalog.componentCount === 1 ? "" : "s"
          } from ${snapshot.source}.`,
        },
        {
          type: "tool-call",
          toolCallId: slashToolCallId("components-tool"),
          toolName: COMPONENT_CATALOG_TOOL_NAME,
          args: toJsonArgs(args),
          argsText: JSON.stringify(args),
        },
      ],
      status: {
        type: "requires-action",
        reason: "tool-calls",
      },
    };
  } catch (error) {
    return {
      content: [
        {
          type: "text",
          text: `Unable to load component catalog: ${
            error instanceof Error ? error.message : String(error)
          }`,
        },
      ],
      status: {
        type: "complete",
        reason: "stop",
      },
    };
  }
};

const extractSetDocumentResult = (
  message: ThreadMessage
): SetDocumentToolResult | null => {
  if (message.role !== "assistant") return null;
  for (const part of message.content) {
    if (part.type !== "tool-call") continue;
    if (part.toolName !== SET_DOCUMENT_TOOL_NAME) continue;
    if (!part.result || part.isError) continue;
    return part.result as SetDocumentToolResult;
  }
  return null;
};

const extractPatchNodeResult = (
  message: ThreadMessage
): PatchNodeToolResult | null => {
  if (message.role !== "assistant") return null;
  for (const part of message.content) {
    if (part.type !== "tool-call") continue;
    if (part.toolName !== PATCH_NODE_TOOL_NAME) continue;
    if (!part.result || part.isError) continue;
    return part.result as PatchNodeToolResult;
  }
  return null;
};

const extractSetDataContextResult = (
  message: ThreadMessage
): SetDataContextToolResult | null => {
  if (message.role !== "assistant") return null;
  for (const part of message.content) {
    if (part.type !== "tool-call") continue;
    if (part.toolName !== SET_DATA_CONTEXT_TOOL_NAME) continue;
    if (!part.result || part.isError) continue;
    return part.result as SetDataContextToolResult;
  }
  return null;
};

const extractTokenAdjustmentResult = (
  message: ThreadMessage
): TokenAdjustmentToolResult | null => {
  if (message.role !== "assistant") return null;
  for (const part of message.content) {
    if (part.type !== "tool-call") continue;
    if (part.toolName !== TOKEN_ADJUSTMENT_TOOL_NAME) continue;
    if (!part.result || part.isError) continue;
    return part.result as TokenAdjustmentToolResult;
  }
  return null;
};

const extractFoundryTokenSyncResult = (
  message: ThreadMessage
): FoundryTokenSyncToolResult | null => {
  if (message.role !== "assistant") return null;
  for (const part of message.content) {
    if (part.type !== "tool-call") continue;
    if (part.toolName !== FOUNDRY_TOKEN_SYNC_TOOL_NAME) continue;
    if (!part.result || part.isError) continue;
    return part.result as FoundryTokenSyncToolResult;
  }
  return null;
};

const extractLoadBundleResult = (
  message: ThreadMessage
): LoadBundleToolResult | null => {
  if (message.role !== "assistant") return null;
  for (const part of message.content) {
    if (part.type !== "tool-call") continue;
    if (part.toolName !== LOAD_BUNDLE_TOOL_NAME) continue;
    if (!part.result || part.isError) continue;
    return part.result as LoadBundleToolResult;
  }
  return null;
};

const extractRenderComponentResult = (
  message: ThreadMessage
): RenderComponentToolResult | null => {
  if (message.role !== "assistant") return null;
  for (const part of message.content) {
    if (part.type !== "tool-call") continue;
    if (part.toolName !== RENDER_COMPONENT_TOOL_NAME) continue;
    if (!part.result || part.isError) continue;
    return part.result as RenderComponentToolResult;
  }
  return null;
};

const extractValidateSchemaResult = (
  message: ThreadMessage
): ValidateSchemaToolResult | null => {
  if (message.role !== "assistant") return null;
  for (const part of message.content) {
    if (part.type !== "tool-call") continue;
    if (part.toolName !== VALIDATE_SCHEMA_TOOL_NAME) continue;
    if (!part.result || part.isError) continue;
    return part.result as ValidateSchemaToolResult;
  }
  return null;
};

const extractComponentCatalogResult = (
  message: ThreadMessage
): ComponentCatalogToolResult | null => {
  if (message.role !== "assistant") return null;
  for (const part of message.content) {
    if (part.type !== "tool-call") continue;
    if (part.toolName !== COMPONENT_CATALOG_TOOL_NAME) continue;
    if (!part.result || part.isError) continue;
    return part.result as ComponentCatalogToolResult;
  }
  return null;
};

const formatCount = (count: number, noun: string) =>
  `${count} ${noun}${count === 1 ? "" : "s"}`;

const isAsyncRunResult = (
  result: ReturnType<ChatModelAdapter["run"]>
): result is AsyncGenerator<ChatModelRunResult, void> =>
  typeof result === "object" &&
  result !== null &&
  Symbol.asyncIterator in result;

const toRunGenerator = (
  result: ReturnType<ChatModelAdapter["run"]>
): AsyncGenerator<ChatModelRunResult, void> => {
  if (isAsyncRunResult(result)) {
    return result;
  }

  return (async function* () {
    yield (await result) as ChatModelRunResult;
  })();
};

export const withToolCommands = (
  adapter: ToolEnabledChatModelAdapterLike,
  options: { systemPromptOverride?: string | null } = {}
): ToolEnabledChatModelAdapter => {
  const run: ChatModelAdapter["run"] = async function* (initialRunOptions) {
    let runOptions = initialRunOptions;

    const interceptedResult = await (async (): Promise<ChatModelRunResult | null> => {
      const resolve = (result: ChatModelRunResult) => Promise.resolve(result);
      const latestUserText = extractLatestUserText(runOptions.messages);
      const normalizedLatestUserText = latestUserText
        ? normalizeCommand(latestUserText)
        : null;
      const isSlashCommandRequest =
        normalizedLatestUserText !== null &&
        Object.keys(TRIGGER_TOOL_MAP).some((trigger) =>
          normalizedLatestUserText.startsWith(trigger)
        );

      const baseOverride = options.systemPromptOverride?.trim() ?? "";
      const includesCatalogSection = baseOverride.includes(
        "OODS COMPONENT CATALOG"
      );
      let catalogPrompt = "";
      try {
        const catalogSection = await getComponentCatalogPromptSection({ limit: 60 });
        catalogPrompt = catalogSection.prompt;
      } catch {
        catalogPrompt = "";
      }
      const overrideParts = [baseOverride];
      if (!includesCatalogSection && catalogPrompt) {
        overrideParts.push(catalogPrompt);
      }
      const override = overrideParts.filter(Boolean).join("\n\n");

      // Inject system prompt override (system messages are single Text parts).
      if (override) {
        const messages = [...runOptions.messages];
        const systemMessageIndex = messages.findIndex((m) => m.role === "system");

        if (systemMessageIndex !== -1) {
          const systemMessage = messages[systemMessageIndex];
          if (systemMessage.role === "system") {
            const existingText = systemMessage.content[0]?.text ?? "";
            const mergedText = existingText
              ? `${existingText}\n\n${override}`
              : override;
            messages[systemMessageIndex] = {
              ...systemMessage,
              content: [{ type: "text", text: mergedText }] as const,
            };
          }
        } else {
          messages.unshift({
            id: `system-override-${Date.now()}`,
            createdAt: new Date(),
            role: "system",
            content: [{ type: "text", text: override }] as const,
            metadata: {
              custom: {},
            },
          });
        }

        runOptions = {
          ...runOptions,
          messages,
        };
      }

      if (latestUserText && normalizedLatestUserText) {
        const normalized = normalizedLatestUserText;

        if (normalized.startsWith(TOKENS_TRIGGER)) {
          const input = latestUserText.slice(TOKENS_TRIGGER.length).trim();
          const syncArgs = parseTokenSyncArgs(input);
          if (syncArgs) {
            return resolve(buildFoundryTokenSyncCall(syncArgs));
          }
          return resolve(buildTokenAdjustmentCall(input));
        }
        if (normalized.startsWith(BUNDLE_TRIGGER)) {
          const input = latestUserText.slice(BUNDLE_TRIGGER.length).trim();
          return resolve(buildLoadBundleCall(input));
        }
        if (normalized.startsWith(RENDER_TRIGGER)) {
          const input = latestUserText.slice(RENDER_TRIGGER.length).trim();
          return resolve(buildRenderComponentCall(input));
        }
        if (normalized.startsWith(VALIDATE_TRIGGER)) {
          const input = latestUserText.slice(VALIDATE_TRIGGER.length).trim();
          return resolve(buildValidateSchemaCall(input));
        }
        if (normalized.startsWith(COMPONENTS_TRIGGER)) {
          return buildComponentCatalogCall();
        }
      }

      const currentMessage = runOptions.unstable_getMessage?.();
      // Only intercept tool results from slash commands. When the LLM
      // autonomously chains tool calls (e.g. compose→patch), the results
      // must flow back to the LLM so it can decide the next step.
      // Slash-command-generated tool calls carry the SLASH_TOOL_PREFIX in
      // their toolCallId, which lets us distinguish them from LLM-initiated
      // tool calls on re-invocation (when latestUserText is absent).
      if (currentMessage && hasSlashToolResult(currentMessage)) {
        const foundrySyncResult = extractFoundryTokenSyncResult(currentMessage);
        if (foundrySyncResult) {
          const unmappedCount =
            foundrySyncResult.unmappedFoundryPaths?.length ?? 0;
          const invalidCount = foundrySyncResult.invalidPaths?.length ?? 0;
          const warnings =
            unmappedCount + invalidCount > 0
              ? ` ${formatCount(unmappedCount, "unmapped path")}, ${formatCount(
                  invalidCount,
                  "invalid path"
                )}.`
              : "";

          return resolve({
            content: [
              {
                type: "text",
                text: `Foundry canonical sync applied: ${formatCount(
                  foundrySyncResult.appliedCount ?? 0,
                  "token"
                )}. Preserved ${formatCount(
                  foundrySyncResult.preservedOverrideCount ?? 0,
                  "manual override"
                )}.${warnings}`,
              },
            ],
            status: {
              type: "complete",
              reason: "stop",
            },
          });
        }

        const tokenResult = extractTokenAdjustmentResult(currentMessage);
        if (tokenResult) {
          const appliedCount = tokenResult.appliedCount ?? 0;
          const invalidCount = tokenResult.invalidPaths?.length ?? 0;
          const invalidNote =
            invalidCount > 0
              ? ` ${formatCount(invalidCount, "invalid path")} blocked.`
              : "";
          return resolve({
            content: [
              {
                type: "text",
                text: `Token update applied: ${formatCount(
                  appliedCount,
                  "change"
                )}.${invalidNote}`,
              },
            ],
            status: {
              type: "complete",
              reason: "stop",
            },
          });
        }

        const bundleResult = extractLoadBundleResult(currentMessage);
        if (bundleResult) {
          const componentCount = bundleResult.componentCount ?? 0;
          const tokenCount = bundleResult.tokenSuggestionCount ?? 0;
          const errorNote =
            bundleResult.errors && bundleResult.errors.length > 0
              ? ` Errors: ${bundleResult.errors.join(" ")}`
              : "";
          return resolve({
            content: [
              {
                type: "text",
                text: `Stage1 bundle loaded: ${formatCount(
                  componentCount,
                  "component"
                )}, ${formatCount(tokenCount, "token suggestion")}.${errorNote}`,
              },
            ],
            status: {
              type: "complete",
              reason: "stop",
            },
          });
        }

        const renderResult = extractRenderComponentResult(currentMessage);
        if (renderResult) {
          const errorNote =
            renderResult.errors && renderResult.errors.length > 0
              ? ` Errors: ${renderResult.errors.join(" ")}`
              : "";
          return resolve({
            content: [
              {
                type: "text",
                text: renderResult.rendered
                  ? "Component document applied. Preview rendering."
                  : `Component render failed.${errorNote}`,
              },
            ],
            status: {
              type: "complete",
              reason: "stop",
            },
          });
        }

        const validateResult = extractValidateSchemaResult(currentMessage);
        if (validateResult) {
          const errorCount = validateResult.errors?.length ?? 0;
          const warningCount = validateResult.warnings?.length ?? 0;
          const errorNote =
            errorCount > 0
              ? ` ${formatCount(errorCount, "error")}: ${validateResult.errors.join("; ")}`
              : "";
          const warningNote =
            warningCount > 0 ? ` ${formatCount(warningCount, "warning")}.` : "";
          return resolve({
            content: [
              {
                type: "text",
                text: validateResult.valid
                  ? `Schema validation passed.${warningNote}`
                  : `Schema validation failed.${errorNote}${warningNote}`,
              },
            ],
            status: {
              type: "complete",
              reason: "stop",
            },
          });
        }

        const componentCatalogResult =
          extractComponentCatalogResult(currentMessage);
        if (componentCatalogResult) {
          return resolve({
            content: [
              {
                type: "text",
                text: `Component catalog listed: ${formatCount(
                  componentCatalogResult.componentCount,
                  "component"
                )} from ${componentCatalogResult.source}.`,
              },
            ],
            status: {
              type: "complete",
              reason: "stop",
            },
          });
        }

        const docResult = extractSetDocumentResult(currentMessage);
        if (docResult) {
          const errorNote =
            docResult.errors && docResult.errors.length > 0
              ? ` Errors: ${docResult.errors.join(" ")}`
              : "";
          return resolve({
            content: [
              {
                type: "text",
                text: docResult.saved
                  ? `Document set: ${formatCount(
                      docResult.nodeCount,
                      "node"
                    )}, ${formatCount(
                      docResult.componentCount,
                      "component"
                    )}. Preview rendering.`
                  : `Document failed.${errorNote}`,
              },
            ],
            status: {
              type: "complete",
              reason: "stop",
            },
          });
        }

        const patchResult = extractPatchNodeResult(currentMessage);
        if (patchResult) {
          const errorNote =
            patchResult.errors && patchResult.errors.length > 0
              ? ` Errors: ${patchResult.errors.join(" ")}`
              : "";
          return resolve({
            content: [
              {
                type: "text",
                text: patchResult.patched
                  ? `Node "${patchResult.nodeId}" patched. Preview re-rendering.`
                  : `Patch failed for "${patchResult.nodeId}".${errorNote}`,
              },
            ],
            status: {
              type: "complete",
              reason: "stop",
            },
          });
        }

        const dataContextResult = extractSetDataContextResult(currentMessage);
        if (dataContextResult) {
          const errorNote =
            dataContextResult.errors && dataContextResult.errors.length > 0
              ? ` Errors: ${dataContextResult.errors.join(" ")}`
              : "";
          return resolve({
            content: [
              {
                type: "text",
                text: dataContextResult.updated
                  ? `Data context updated: ${formatCount(
                      dataContextResult.keyCount,
                      "key"
                    )}. Bindings will resolve on next render.`
                  : `Data context update failed.${errorNote}`,
              },
            ],
            status: {
              type: "complete",
              reason: "stop",
            },
          });
        }
      }

      return null;
    })();

    if (interceptedResult) {
      yield interceptedResult;
      return;
    }

    yield* toRunGenerator(adapter.run(runOptions));
  };

  const executeTool: ToolEnabledChatModelAdapter["executeTool"] = async ({
    toolName,
    args,
    toolCallId,
    abortSignal,
  }) => {
    // Route to local executors
    if (toolName === RENDER_COMPONENT_TOOL_NAME) {
      return await renderComponent(args as RenderComponentToolArgs);
    }

    if (toolName === VALIDATE_SCHEMA_TOOL_NAME) {
      return await validateSchema(args as ValidateSchemaToolArgs);
    }

    // set_document / patch_node / forge_regenerate are GATED through the
    // suggest-and-confirm tool UI (DocumentToolUI / ForgeRegenerateToolUI) —
    // only a human Accept applies the change. This dispatcher is not wired to
    // the LocalRuntime path, but guard it so a future mis-wiring can never
    // silently mutate the document without confirmation.
    if (
      toolName === SET_DOCUMENT_TOOL_NAME ||
      toolName === PATCH_NODE_TOOL_NAME ||
      toolName === FORGE_REGENERATE_TOOL_NAME
    ) {
      return {
        error: `"${toolName}" is gated through the suggest-and-confirm UI and cannot be auto-executed.`,
      };
    }

    if (toolName === SET_DATA_CONTEXT_TOOL_NAME) {
      return executeSetDataContext(args as SetDataContextToolArgs);
    }

    if (toolName === TOKEN_ADJUSTMENT_TOOL_NAME) {
      const toolArgs = args as TokenAdjustmentToolArgs;
      const tokenStore = useTokenStateStore.getState();
      const { validChanges, invalidPaths } = buildTokenChangeSummary(
        tokenStore.tokens,
        toolArgs.changes ?? {}
      );
      tokenStore.setTokens(validChanges, "manual");
      return {
        applied: true,
        appliedCount: Object.keys(validChanges).length,
        invalidPaths,
        resolvedAt: new Date().toISOString(),
      } satisfies TokenAdjustmentToolResult;
    }

    if (toolName === COMPONENT_CATALOG_TOOL_NAME) {
      return executeComponentCatalog(args as Partial<ComponentCatalogToolArgs>);
    }

    // Delegate to wrapped adapter's executeTool for tools without local executors
    // (e.g. load_bundle, foundry_token_sync, etc.)
    if (adapter.executeTool) {
      return await adapter.executeTool({ toolName, args, toolCallId, abortSignal });
    }

    return { error: `No executor registered for tool "${toolName}".` };
  };

  return {
    run,
    executeTool,
  };
};
